repo_url: https://github.com/MurphLu/MurphLu.github.io.git
repo_name: Murph's NoteBook
site_name: Murph's NoteBook
site_url: https://murphlu.github.io/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  icon:
    repo: fontawesome/brands/github

plugins:
  - search