repo_url: https://github.com/MurphLu/MurphLu.github.io.git
repo_name: Murph's NoteBook
site_name: Murph's NoteBook
site_url: https://murphlu.github.io/
theme:
  name: material
  highlightjs: true
  assets:
    javascript:
      - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js

  stylesheets:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

# markdown_extensions:
#   - pymdownx.highlight:
#       use_pygments: true
#       linenums: true
extra_javascript:
  - javascripts/highlight.min.js
  - javascripts/highlightjs-line-numbers.min.js
  - javascripts/highlight.js
extra_css:
  - javascripts/highlight.min.css